/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examinationapplication;

import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Sayyed Abrar Akhtar
 */
public class QuizzJFrame extends javax.swing.JFrame {

    /**
     * Creates new form QuizzJFrame
     */
    int id=1, qid, /*setid,*/ score=0, counter, count;
    String correctans, selectedAns, setname;
    MySQLConnect mySqlConn;
    private static int examineeid, setid;

    
    //javax.swing.ButtonGroup buttonGroup;
    public QuizzJFrame(int qsetid, int eid) {
        
        initComponents();
        
        QuizzJFrame.setid = qsetid;
        QuizzJFrame.examineeid = eid;
        setLocationRelativeTo(null);  // *** center appearance of the app ***
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup1.add(jRadioButtonO1);
        buttonGroup1.add(jRadioButtonO2);
        buttonGroup1.add(jRadioButtonO3);
        buttonGroup1.add(jRadioButtonO4);
        buttonGroup1.add(jRadioButtonO5);
        mySqlConn = new MySQLConnect();
        counter = 0;
        retrieveSetname(setid);
        
        count = countQuestion(setid);
        checkId(id, setid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonO1 = new javax.swing.JRadioButton();
        jButtonNext = new javax.swing.JButton();
        jRadioButtonO4 = new javax.swing.JRadioButton();
        jRadioButtonO3 = new javax.swing.JRadioButton();
        jRadioButtonO2 = new javax.swing.JRadioButton();
        jRadioButtonO5 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaQ = new javax.swing.JTextArea();
        jButtonNavigator = new javax.swing.JButton();
        jLabelQ = new javax.swing.JLabel();
        jLabelQ1 = new javax.swing.JLabel();
        jLabelQ2 = new javax.swing.JLabel();
        jLabelQ3 = new javax.swing.JLabel();
        jLabelQ4 = new javax.swing.JLabel();
        jLabelQ5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(41, 128, 185));

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("THE QUIZZ GAME");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(450, 450, 450))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jRadioButtonO1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jRadioButtonO1.setText("jRadioButton1");
        jRadioButtonO1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonO1MouseClicked(evt);
            }
        });

        jButtonNext.setBackground(new java.awt.Color(41, 128, 185));
        jButtonNext.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jButtonNext.setText("Next");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jRadioButtonO4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jRadioButtonO4.setText("jRadioButton1");
        jRadioButtonO4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonO4MouseClicked(evt);
            }
        });

        jRadioButtonO3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jRadioButtonO3.setText("jRadioButton1");
        jRadioButtonO3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonO3MouseClicked(evt);
            }
        });

        jRadioButtonO2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jRadioButtonO2.setText("jRadioButton1");
        jRadioButtonO2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonO2MouseClicked(evt);
            }
        });

        jRadioButtonO5.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jRadioButtonO5.setText("jRadioButton1");
        jRadioButtonO5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonO5MouseClicked(evt);
            }
        });

        jTextAreaQ.setColumns(20);
        jTextAreaQ.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jTextAreaQ.setRows(5);
        jScrollPane2.setViewportView(jTextAreaQ);

        jButtonNavigator.setBackground(new java.awt.Color(44, 62, 80));
        jButtonNavigator.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonNavigator.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNavigator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/undo2.png"))); // NOI18N
        jButtonNavigator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNavigatorActionPerformed(evt);
            }
        });

        jLabelQ.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabelQ.setText("Question ");

        jLabelQ1.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabelQ1.setText("1.");

        jLabelQ2.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabelQ2.setText("2.");

        jLabelQ3.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabelQ3.setText("3.");

        jLabelQ4.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabelQ4.setText("4.");

        jLabelQ5.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabelQ5.setText("5.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelQ)
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelQ2)
                                    .addComponent(jLabelQ1)
                                    .addComponent(jLabelQ3)
                                    .addComponent(jLabelQ4)
                                    .addComponent(jLabelQ5))
                                .addGap(27, 27, 27)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonO3)
                            .addComponent(jRadioButtonO2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1059, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonO4)
                            .addComponent(jRadioButtonO5)
                            .addComponent(jRadioButtonO1))
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNavigator, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(477, 477, 477))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNavigator, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabelQ)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonO2)
                            .addComponent(jLabelQ1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonO3)
                            .addComponent(jLabelQ2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonO4)
                            .addComponent(jLabelQ3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonO5)
                            .addComponent(jLabelQ4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonO1)
                            .addComponent(jLabelQ5))
                        .addContainerGap(119, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
   
        
    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        
        
        if (counter < count ){
        counter = counter + 1;
        jLabelQ.setText("Question "+ counter +":");
        totalScore();
        if(counter == count-1){
            jButtonNext.setText("Finish");
            counter = counter + 1;
        }
        
    
        checkId(id, setid);
        buttonGroup1.clearSelection();
        System.out.println("count: "+ count + " counter: " + counter + " id: " + id + " score: " + score );
        } 
        
        else if (counter == count){
            totalScore();
            storeResult();
            JOptionPane.showMessageDialog(null, storeResult());
            ResultJFrame result = new ResultJFrame(score, examineeid, setid);
            result.setVisible(true);
            dispose();
        }
        
  
    }//GEN-LAST:event_jButtonNextActionPerformed

    
    public Boolean storeResult(){ 
        String query = "INSERT INTO `result` (`examineeid`, `score`, `setname`) VALUES( '"+ examineeid + "', '" + score  + "', '" + setname +"')";         
        System.out.println(query);
        return mySqlConn.executeSQLQuery(query, "Updated");

    }
    
    public Boolean retrieveSetname(int qsetid) {
        String query = "SELECT setname FROM questionset where id = " + qsetid;
        ResultSet resultset;
        resultset = mySqlConn.retrieveData(query);
        try{
            if (resultset.next()){
                setname = resultset.getString("setname");
                return true;
            } 
            
        } catch (SQLException ex){
            System.out.println("Setname Not retrieved: " + ex);
        }
        return false;
    }
    
    private void totalScore(){
        if (selectedAns.equals(correctans)){
            score += 1;
        }
    }
    
    private void jRadioButtonO1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonO1MouseClicked
        selectedAns = "a";
    }//GEN-LAST:event_jRadioButtonO1MouseClicked

    private void jRadioButtonO2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonO2MouseClicked
        selectedAns = "b";
    }//GEN-LAST:event_jRadioButtonO2MouseClicked

    private void jRadioButtonO3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonO3MouseClicked
        selectedAns = "c";
    }//GEN-LAST:event_jRadioButtonO3MouseClicked

    private void jRadioButtonO4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonO4MouseClicked
        selectedAns = "d";
    }//GEN-LAST:event_jRadioButtonO4MouseClicked

    private void jRadioButtonO5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonO5MouseClicked
        selectedAns = "e";
    }//GEN-LAST:event_jRadioButtonO5MouseClicked

    private void jButtonNavigatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNavigatorActionPerformed

        AdminOrExamineeJFrame navigator = new AdminOrExamineeJFrame();
        navigator.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonNavigatorActionPerformed

    /**
     * @param setid
     * @return 
     */
    
    
    
    
    public int countQuestion(int setid) {
        
        String query = "SELECT COUNT(id) AS 'totalq' FROM questions where setid = " + setid;
        ResultSet resultset;
        resultset = mySqlConn.retrieveData(query);
        try{
            if (resultset.next()){
                count = resultset.getInt("totalq");
            } 
            
        } catch (SQLException ex){
            System.out.println("Error in loadData method in line 251: " + ex);
        }
        return count;
    }
    
    private void checkId(int qtid, int setid) {
        String query = "select * from questions where id = " + qtid +" and setid = " + setid;
        ResultSet resultset;
        resultset = mySqlConn.retrieveData(query);
        try{
            if (resultset.next()){
                qid = id;
                loadData(qid, setid);
                id = id+1;
            } else {
                id = id+1;
                checkId(id, setid);
            }
            
        } catch (SQLException ex){
            System.out.println("Error in loadData method in line 251: " + ex);
        }
    }
    
    private void loadData(int id, int setid){
        String query = "select * from questions where id = " + id +" and setid = " + setid;
        ResultSet resultset; 
        
        
        resultset = mySqlConn.retrieveData(query);
        try{
        if (resultset.next()){
            jTextAreaQ.setText(resultset.getString("question"));
            jTextAreaQ.setEditable(false);
            jRadioButtonO1.setText(resultset.getString("a"));
            jRadioButtonO2.setText(resultset.getString("b"));
            jRadioButtonO3.setText(resultset.getString("c"));
            jRadioButtonO4.setText(resultset.getString("d"));
            jRadioButtonO5.setText(resultset.getString("e"));
            correctans = resultset.getString("correctanswer");
           
        }
            
        } catch (SQLException ex){
            System.out.println("Error in loadData method in line 251: " + ex);
        }
        
    }
  
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizzJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new QuizzJFrame(setid, examineeid).setVisible(true);
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonNavigator;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelQ;
    private javax.swing.JLabel jLabelQ1;
    private javax.swing.JLabel jLabelQ2;
    private javax.swing.JLabel jLabelQ3;
    private javax.swing.JLabel jLabelQ4;
    private javax.swing.JLabel jLabelQ5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonO1;
    private javax.swing.JRadioButton jRadioButtonO2;
    private javax.swing.JRadioButton jRadioButtonO3;
    private javax.swing.JRadioButton jRadioButtonO4;
    private javax.swing.JRadioButton jRadioButtonO5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaQ;
    // End of variables declaration//GEN-END:variables
}
