/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examinationapplication;

import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Sayyed Abrar Akhtar
 */
public class UpdateExamineeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form UpdateExamineeJFrame
     */
    int operation =0;
    int row=0;
    int examineeId;
    MySQLConnect MySqlConn;
    public UpdateExamineeJFrame() {
        initComponents();
        setLocationRelativeTo(null);  // *** center appearance of the app ***
        MySqlConn =  new MySQLConnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();
        emailTxtField = new javax.swing.JTextField();
        contactTxtField = new javax.swing.JTextField();
        usernameTxtField = new javax.swing.JTextField();
        pswdPasswordField = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnUpdateAdmin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableExaminee = new javax.swing.JTable();
        cnfmpswdPasswordField = new javax.swing.JPasswordField();
        genderTxtField = new javax.swing.JTextField();
        jButtonDelExaminee = new javax.swing.JButton();
        jButtonNavigator = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(41, 128, 185));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(1141, 517));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("UPDATE EXAMINEE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(445, 445, 445))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        nameTxtField.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        nameTxtField.setName("nameTxtField"); // NOI18N

        emailTxtField.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        emailTxtField.setName("emailTxtField"); // NOI18N

        contactTxtField.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        contactTxtField.setName("contactTxtField"); // NOI18N

        usernameTxtField.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        usernameTxtField.setName("usernameTxtField"); // NOI18N

        pswdPasswordField.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        pswdPasswordField.setName("pswdPasswordField"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel9.setText("Confirm Password:");

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel8.setText("Password:");

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel7.setText("Username:");

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel6.setText("Contact:");

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel5.setText("Gender:");

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel4.setText("Email Id:");

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel3.setText("Full Name:");

        btnUpdateAdmin.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btnUpdateAdmin.setText("Update");
        btnUpdateAdmin.setName("btnUpdateAdmin"); // NOI18N
        btnUpdateAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAdminActionPerformed(evt);
            }
        });

        tableExaminee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Username", "Gender", "Contact", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableExaminee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableExamineeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableExaminee);

        cnfmpswdPasswordField.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        cnfmpswdPasswordField.setName("cnfmpswdPasswordField"); // NOI18N

        genderTxtField.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        genderTxtField.setName("usernameTxtField"); // NOI18N

        jButtonDelExaminee.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButtonDelExaminee.setText("Delete");
        jButtonDelExaminee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelExamineeActionPerformed(evt);
            }
        });

        jButtonNavigator.setBackground(new java.awt.Color(44, 62, 80));
        jButtonNavigator.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonNavigator.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNavigator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/undo2.png"))); // NOI18N
        jButtonNavigator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNavigatorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(contactTxtField)
                                    .addComponent(pswdPasswordField)
                                    .addComponent(nameTxtField))
                                .addGap(40, 40, 40))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(genderTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnUpdateAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(jButtonDelExaminee, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(emailTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                                    .addComponent(usernameTxtField)
                                    .addComponent(cnfmpswdPasswordField)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNavigator, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonNavigator, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(emailTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(usernameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pswdPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cnfmpswdPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDelExaminee)
                    .addComponent(btnUpdateAdmin)
                    .addComponent(genderTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1284, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
  
     void loadData(String uname, String pass) {
        
        String query = "select * from examinee where username = '" + uname + "' and password = '" + pass + "'";
        ResultSet resultset;
        
        DefaultTableModel model = (DefaultTableModel) tableExaminee.getModel();
        try {
           resultset = MySqlConn.retrieveData(query);
           if (resultset.next()) {
            examineeId = resultset.getInt("id");
            String name = resultset.getString("name");
            String examineename = resultset.getString("username");
            String email = resultset.getString("email");
            String contact = resultset.getString("contact");
            String gender = resultset.getString("gender");
            nameTxtField.setText(name);
            emailTxtField.setText(email);
            contactTxtField.setText(contact);
            usernameTxtField.setText(examineename);
            genderTxtField.setText(gender);
            pswdPasswordField.setText("");
            cnfmpswdPasswordField.setText("");
            
            model.addRow(new Object[]{examineeId, name, examineename,gender,contact, email});
            
            //model.addRow(new Object[]{resultset.getInt("id"),resultset.getString("name"), resultset.getString("username"),resultset.getString("gender"),resultset.getString("contact"), resultset.getString("email")});
               
           
           }   
        } catch (SQLException e) {
           JOptionPane.showMessageDialog(null, "Examinee details not retrieved: " + e);
        }
    }
    // load examinee inforamtion data to table

    /**
     *
     */
    public void loadExamineeData() {
        String query = "select id, name, username, gender, contact, email from examinee  ORDER BY `examinee`.`id` DESC";
        ResultSet resultset;
        try {
           resultset = MySqlConn.retrieveData(query);
           DefaultTableModel model = (DefaultTableModel) tableExaminee.getModel();
           while(resultset.next())
           {
            model.addRow(new Object[]{resultset.getInt("id"),resultset.getString("name"), resultset.getString("username"),resultset.getString("gender"),resultset.getString("contact"), resultset.getString("email")});
               
           }

           
       } catch (SQLException ex) {
       }
    }

    
    // clear all fields input
    private void clearControls(){
        nameTxtField.setText("");
        emailTxtField.setText("");
        contactTxtField.setText("");
        usernameTxtField.setText("");
        pswdPasswordField.setText("");
        cnfmpswdPasswordField.setText("");
        genderTxtField.setText("");
    }
    
    
    public Boolean updateExaminee(String Jframename, String Jframepassword, String JframeconfirmPassword, String Jframeemail, String Jframecontact, String Jframegender, int eid) {
        String name = Jframename;
        String contact = Jframecontact;
        String email = Jframeemail;
        String password = Jframepassword;
        String confirmPassword = JframeconfirmPassword;
        String findgender =Jframegender;
        String gender;
        
        switch (findgender) {
            case "Male":
            case "male":
                gender = "Male";
                break;
            case "Female":
            case "female":
                gender = "Female";
                break;
            case "Other":
            case "other":
                gender = "Other";
                break;
            default:
                JOptionPane.showMessageDialog(null, "Gender can be 'Male' or 'Female' or 'Other' ");
                gender = "";
                break;
        }
        if (pswdPasswordField.getText().equals(cnfmpswdPasswordField.getText())) {
            password = pswdPasswordField.getText();
        } else {
            JOptionPane.showMessageDialog(null, "Password did not matched!!");
            pswdPasswordField.setText("");
            cnfmpswdPasswordField.setText("");
            pswdPasswordField.grabFocus();
            return false;
        } 
        Boolean isEmpty = isFieldEmpty(name, password, confirmPassword, email, contact);
 
        
        if (!isEmpty){
            
        	String query = "update examinee set name = '" + name + "', email = '" + email + "', password = '" + password + "', gender = '" + gender + "', contact = '" + contact + "' where id =" +eid;
            MySqlConn.executeSQLQuery(query, "Updated");
            System.out.println(query);
   
            return true;
            
        } 
        return false;
    }
 
    public Boolean isFieldEmpty(String name, String password, String confirmPassword, String email, String contact){
        
        if(name.trim().equals("") ||
           email.trim().equals("")||
           contact.trim().equals("")||
           password.trim().equals("")||
           confirmPassword.trim().equals("")
            )
        {
            JOptionPane.showMessageDialog(null, "All fields must be filled!!");
            return true;
        }
        return false;
    }   
    
    
    
    private void btnUpdateAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAdminActionPerformed
    	
    	String name = nameTxtField.getText();
        String email = emailTxtField.getText();
        String contact = contactTxtField.getText();
        String username = usernameTxtField.getText();
        String password = pswdPasswordField.getText();
        String confirmPassword = cnfmpswdPasswordField.getText();
        String findgender =genderTxtField.getText();
        String gender;
        switch (findgender) {
            case "Male":
            case "male":
                gender = "Male";
                break;
            case "Female":
            case "female":
                gender = "Female";
                break;
            case "Other":
            case "other":
                gender = "Other";
                break;
            default:
                JOptionPane.showMessageDialog(null, "Gender can be 'Male' or 'Female' or 'Other' ");
                gender = "";
                break;
        }
    	
    	Boolean examinee = updateExaminee(name, password, confirmPassword, email, contact, gender, examineeId);
    	if(examinee) {
    		clearControls();
	        AdminOrExamineeJFrame home = new AdminOrExamineeJFrame();
	        home.setVisible(true);
	        dispose();
		}

    }//GEN-LAST:event_btnUpdateAdminActionPerformed

    private void tableExamineeMouseClicked(java.awt.event.MouseEvent evt) {                                           
        operation=1;
        row = tableExaminee.getSelectedRow();
        
        examineeId = (int) tableExaminee.getModel().getValueAt(row,0);
        String value = tableExaminee.getModel().getValueAt(row,1).toString();
         nameTxtField.setText(value);
        value = tableExaminee.getModel().getValueAt(row,2).toString();
        usernameTxtField.setText(value);
        value = tableExaminee.getModel().getValueAt(row,3).toString();
        genderTxtField.setText(value);
        value = tableExaminee.getModel().getValueAt(row,4).toString();
        contactTxtField.setText(value);
        value = tableExaminee.getModel().getValueAt(row,5).toString();
        emailTxtField .setText(value);
        
    }

   
    
    
    private void jButtonDelExamineeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelExamineeActionPerformed
        //Connection con = MySqlConn.getConn();
            try {
                String deleteQ = "DELETE FROM `examinee` WHERE `examinee`.`id` = "  + examineeId;
                MySqlConn.executeSQLQuery(deleteQ, "Deleted");
                clearControls();
                ExamineeLoginJFrame frame = new ExamineeLoginJFrame();
                frame.setVisible(true);
                dispose();
            } catch (Exception ex){
                JOptionPane.showMessageDialog(null, "Question not deleted: " + ex);
            }
    }//GEN-LAST:event_jButtonDelExamineeActionPerformed

    
    
    
    private void jButtonNavigatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNavigatorActionPerformed
        
        String uname="", key="";
        String query = "select * from examinee where id = " + examineeId;
        ResultSet resultset;
        resultset = MySqlConn.retrieveData(query);
        try {
            if(resultset.next()){
                uname = resultset.getString("username");
                key = resultset.getString("password");
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateExamineeJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        DashboardJFrame navigator = new DashboardJFrame(uname, key);
        navigator.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonNavigatorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateExamineeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateExamineeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateAdmin;
    private javax.swing.JPasswordField cnfmpswdPasswordField;
    private javax.swing.JTextField contactTxtField;
    private javax.swing.JTextField emailTxtField;
    private javax.swing.JTextField genderTxtField;
    private javax.swing.JButton jButtonDelExaminee;
    private javax.swing.JButton jButtonNavigator;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JPasswordField pswdPasswordField;
    private javax.swing.JTable tableExaminee;
    private javax.swing.JTextField usernameTxtField;
    // End of variables declaration//GEN-END:variables

    

  
}
